// autogenerated ui file by ittyOS-ui-designer. dont modify manually please <3

#include "ff.h"
#include "fonts.h"
#include "graphics.h"
#include "print.h"
#include "programs.h"
#include "st7789.h"
#include "stm32f4xx_hal.h"
#include "stm32f4xx_hal_adc.h"
#include "system.h"
#include <string.h>

/*
{
  "Base": 0
},
{
  "Img": [
    0,
    0,
    "images/cat.ibi"
  ]
},
{
  "Rect": [
    0,
    0,
    52,
    320,
    25897
  ]
},
{
  "Rect": [
    428,
    0,
    52,
    320,
    25897
  ]
},
{
  "Text": [
    0,
    30,
    "wahoo",
    "Font_16x26",
    65535
  ]
}
*/

FIL testImg0;
void testDrawCallback(int i) {
  int streamBytesAmt = 480 * HOR_LEN * 2;
  for (int o = 0; o < 40; o++) {
    memset(&disp_buf[o * 480 * 2], 0x0000, 480 * 2);
  }
  if (i >= 0 && i <= 4) {
    for (int o = 0; o < 40; o++) {
      int currentY = i * HOR_LEN + o;
      if (currentY >= 0) {
        initSPI(SD_SPI_SPEED);
        FRESULT res = f_lseek(&testImg0, (currentY - 0) * 250 * 2);
        // FRESULT res = FR_OK;
        if (res != FR_OK) {
          print("f_seek failed with code: %d\r\n", res);
        }
        res =
            f_read(&testImg0,
                   &disp_buf[((currentY - i * HOR_LEN) - 0) * 480 * 2 + 0 * 2],
                   250 * 2, 0);
        if (res != FR_OK) {
          print("f_read failed with code: %d\r\n", res);
        }
      }
    }
  }
  if (i >= 0 && i <= 1) {
    writeStringToBuffer(0, 30 - 0 * HOR_LEN, "wahoo", Font_16x26, 0xffff,
                        disp_buf, 480, HOR_LEN);
  }
  if (i >= 0 && i <= 7) {
    for (int o = 0; o < 40; o++) {
      memset_u16(&disp_buf[o * 480 * 2 + 0 * 2], 0x6529, 52 * 2);
      memset_u16(&disp_buf[o * 480 * 2 + 428 * 2], 0x6529, 52 * 2);
    }
  }
  initSPI(LCD_SPI_SPEED);
  // memset_u16(disp_buf, 0xff00, streamBytesAmt);
  ST7789_WriteData(disp_buf, streamBytesAmt);
}

void testDraw() {
  initSPI(SD_MOUNT_SPI_SPEED);
  if (sd_mount() == FR_OK) {
    initSPI(SD_SPI_SPEED);
    FRESULT res = f_open(&testImg0, "images/cat.ibi", FA_READ);
    if (res != FR_OK) {
      print("f_open failed with code: %d", res);
      printFlush(Font_16x26);
      return;
    }
    initSPI(LCD_SPI_SPEED);

    for (int i = 0; i < 320 / HOR_LEN; i++) {
      ST7789_SetAddressWindow(0, i * HOR_LEN, 480 - 1, i * HOR_LEN + 320 - 1);
      // memset_u16(disp_buf, 0xff00, 480 * 320 * 2);
      // ST7789_WriteData(disp_buf, 480 * 320 * 2);
      testDrawCallback(i);
    }

    res = f_close(&testImg0);
    if (res != FR_OK) {
      print("f_close failed with code: %d", res);
      return;
    }
    sd_unmount();
  } else {
    print("waa");
    printFlush(Font_16x26);
    return;
  }
}

void emptyFunction() {}

extern PROGRAM TEST = {"test", testDraw, emptyFunction};